In [101]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import tensorflow as tf

In [102]:
with open('classificiation_label_encoder.pkl','rb') as file:
    label = pickle.load(file)

In [103]:
with open('classificiation_one_hot_encoder.pkl','rb') as file:
    ohe = pickle.load(file)

In [104]:
with open('classificiation_scaler.pkl','rb') as file:
    scaler = pickle.load(file)

In [105]:
model = load_model('classification_model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [106]:
user= {'Pclass':1,'Sex':'male','SibSp':2,'Parch':1,'Fare':76,'Embarked':'Cheboug'}

In [107]:
user_df = pd.DataFrame([user])

In [108]:
user_df

   Pclass   Sex  SibSp  Parch  Fare Embarked
0       1  male      2      1    76  Cheboug

In [109]:
user_df['Sex'] = label.transform(user_df['Sex'])

In [110]:
user_df

   Pclass  Sex  SibSp  Parch  Fare Embarked
0       1    1      2      1    76  Cheboug

In [111]:
embarked = ohe.transform(user_df[['Embarked']])

In [112]:
embarked_df = pd.DataFrame(embarked,columns=ohe.get_feature_names_out())

In [113]:
embarked_df

   Embarked_Cheboug  Embarked_Queenstown  Embarked_Southampton
0               1.0                  0.0                   0.0

In [114]:
user_df = pd.concat([user_df.drop(columns=['Embarked']),embarked_df],axis=1)

In [115]:
user_df

   Pclass  Sex  ...  Embarked_Queenstown  Embarked_Southampton
0       1    1  ...                  0.0                   0.0

[1 rows x 8 columns]

In [116]:
user_df[['Pclass','SibSp','Parch','Fare']] =  scaler.transform(user_df[['Pclass','SibSp','Parch','Fare']])

In [117]:
user_df

     Pclass  Sex  ...  Embarked_Queenstown  Embarked_Southampton
0 -1.568865    1  ...                  0.0                   0.0

[1 rows x 8 columns]

In [118]:
y = model.predict(user_df)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step

In [119]:
y

array([[0.33961472]], dtype=float32)

In [120]:
y = y[0][0]

In [121]:
y

np.float32(0.33961472)

In [122]:
if y > 0.5:
    print('Passenger will survive')
else:
    print('Passenger wont survive')

Passenger wont survive